### PR TITLE
 Value of the custom callback

### PR DESCRIPTION
**Pull request by netstao**
Custom value jsonp callback

### CODE REVIEW

**Comment by leozdgao** [comment]
+1. Has the same requirement of custom jsonp callback.

**Comment by alex-bowers** [comment]
:+1: this worked for us.

**Comment by jbrooksuk** [comment]
@yyx990803 any chance we could see this merged and tagged? It's stopping us from interacting with websites that haven't enabled CORS.

**Comment by gkatsanos** [comment]
@yyx990803 can you review and tag this?

**Comment by steffans** [comment]
See issue #477

**Pull request closed without merging**
