### PR TITLE
Add Vue 2.x typings for TypeScript

### PR DESCRIPTION
**Pull request by dl00**
The current implementation of `@types/vue-resource` was causing my build to fail because it was pulling the empty `@types/vue` repo. I designed this fork in order to solve this problem for my project, and it is working with only a minor caveat from what I can tell. The implementation style is influenced by the typings for the official Vue project, Vuex, and vue-router type implementations.

The only problem that I have encountered at this point is the static Vue members "http" and "resource". Unfortunately due to a limitation in typescript (https://github.com/Microsoft/TypeScript/issues/819). The easiest way I have found to resolve this problem is to run Vue.resource or Vue.http calls in a separate plain .js file.

Please let me know if you want me to add documentation, tests, or something like that.

### CODE REVIEW

**Comment by steffans** [comment]
Thanks, i don't use typescript in project atm. You can explain some basics in the docs config part, https://github.com/pagekit/vue-resource/blob/develop/docs/config.md

Then i will merge you PR and for the next release!

**Comment by amarox** [comment]
Status? Typescript still not allowed?

**Comment by dl00** [comment]
I'm sorry, I forgot I ever made this merge request :)

I added the docs (they are not that long since it should work out of the box). You can merge if you want. I have been using this vue-resource repository in my project for awhile now so it should work.

**Comment by amarox** [comment]
Thanks! @steffans can you merge this PR?

**Comment by amarox** [comment]
Thanks!

**Pull request merged**
